apiVersion: v1
kind: Service
metadata:
  name: "nsgate"
  labels:
    name: "nsgate"
    major: "<% major %>"
spec:
  selector:
    name: "nsgate"
    major: "<% major %>"
  ports:
  - port: 80
    targetPort: 80
    name: "http"
  - port: 443
    targetPort: 443
    name: "https"
  - port: 8000
    targetPort: 8000
    name: "app1"
  - port: 8080
    targetPort: 8080
    name: "app2"
  - port: 1113
    targetPort: 1113
    name: "app3"
  - port: 2113
    targetPort: 2113
    name: "app4"
  type: "LoadBalancer"
