apiVersion: v1
kind: ReplicationController
metadata:
  name: "nsgate<% cli.id %>"
  labels:
    name: "nsgate"
    major: "<% major %>"
    minor: "<% minor %>"
    build: "<% cli.id %>"
spec:
  replicas: 2
  selector:
    name: "nsgate"
    major: "<% major %>"
    minor: "<% minor %>"
    build: "<% cli.id %>"
  template:
    metadata:
      labels:
        name: "nsgate"
        major: "<% major %>"
        minor: "<% minor %>"
        build: "<% cli.id %>"
    spec:
      containers:
      - name: "nsgate"
        image: "<% image %>:<% major %>.<% minor %>.<% cli.id %>"
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            name: "http"
          - containerPort: 443
            name: "https"
          - containerPort: 8000
            name: "app1"
          - containerPort: 8080
            name: "app2"
          - containerPort: 1113
            name: "app3"
          - containerPort: 2113
            name: "app4"
        volumeMounts:
        - name: web-ssl
          readOnly: true
          mountPath: /etc/ssl
      volumes:
      - name: web-ssl
        secret:
          secretName: web-ssl
