apiVersion: v0
kind: HiveConfig
spec:
  kubernetes:
    deploymentStrategy: Recreate

  configuration:
    domain:    adaptivecluster.com

    image: weareadaptive/nsgate
    major: 0
    minor: 1

    certificates:
      pem:
        __b64__: "certificates/server.pem"
      key:
        __b64__: "certificates/server.key"
