apiVersion: v1
kind: Service
metadata:
  name: "<% name %>"
  labels:
    name: "<% name %>"
    public: "true"
spec:
  selector:
    name: "<% name %>"
  ports:
  - port: 443
    targetPort: 8080
    name: "https"
