apiVersion: v1
kind: ReplicationController
metadata:
  name: "<% name %>"
  labels:
    name: "<% name %>"
spec:
  replicas: 1
  selector:
    name: "<% name %>"
  template:
    metadata:
      labels:
        name: "<% name %>"
    spec:
      containers:
        - name: "<% name %>"
          image: "<% image %>:<% major %>.<% minor %>"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: "http"
            - containerPort: 50000 
              name: "slaves"

          volumeMounts: 
            # Move Jenkins home to a volume for persistency
            - name: "jenkins-data"
              mountPath: "/var/jenkins_home"
              
            # Give access to the node docker daemon
            - name: "docker-socket"
              mountPath: "/var/run/docker.sock"
      volumes:
        # Move Jenkins home to a volume for persistency
        - name: "jenkins-data"
          gcePersistentDisk:
            pdName: jenkins-data-disk
            fsType: ext4
        - name: "docker-socket"
          hostPath:
            path: "/var/run/docker.sock"
