# The docker version running on GoogleContainerEngine is 1.8
#   as the build of ReactiveTrader is done using the docker volume feature (version 1.9),
#   this deployment will be used after the GoogleContainerEngine update
apiVersion: v0
kind: HiveConfig
spec:
  kubernetes:
    deploymentStrategy: Recreate
    gcePersistentDisk:
      # For now, this is done manually with:
      # ./hive gcloud cli compute disks create --zone=europe-west1-c --size=20GB jenkins-data-disk
      - name: jenkins-data-disk
        size: "20GB"

  configuration:
    project: ci
    name:    jenkins
    major:   0
    minor:   0
    image:   weareadaptive/jenkins
